version: "3"

services:
  backend:
    image: mingchanoknan/backend:lastest
    ports:
      - 8088:80
    build: ./backend
    healthcheck:
      test: curl --fail http://54.90.204.114:8088 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  frontend:
    image: mingchanoknan/frontend:lastest
    ports:
      - 3000:3000
    build: ./frontend
    healthcheck:
      test: curl --fail http://54.90.204.114:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s